//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainmentX
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentGameHistory
    {
        public int IdComment { get; set; }
        public int IdUser { get; set; }
        public System.DateTime Datetime { get; set; }
        public string ColorLike { get; set; }
        public string ColorDisLike { get; set; }
    
        public virtual CommentsGame CommentsGame { get; set; }
    }
}
