//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainmentX
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentsGame
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommentsGame()
        {
            this.CommentGameHistory = new HashSet<CommentGameHistory>();
        }
    
        public int IdComments { get; set; }
        public string Text { get; set; }
        public int IdGame { get; set; }
        public int IdUser { get; set; }
        public System.DateTime Datetime { get; set; }
        public int CountLike { get; set; }
        public int CountDisLike { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentGameHistory> CommentGameHistory { get; set; }
        public virtual Games Games { get; set; }
        public virtual Users Users { get; set; }
    }
}
