//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainmentX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Games()
        {
            this.CommentsGame = new HashSet<CommentsGame>();
            this.FavotritesGame = new HashSet<FavotritesGame>();
            this.MarkGame = new HashSet<MarkGame>();
            this.GamesToGenres = new HashSet<GamesToGenres>();
            this.GamesToPlatform = new HashSet<GamesToPlatform>();
            this.GameTrailer = new HashSet<GameTrailer>();
            this.InterfaceLanguage = new HashSet<InterfaceLanguage>();
            this.ScreenshotsGame = new HashSet<ScreenshotsGame>();
            this.Torrents = new HashSet<Torrents>();
            this.VoiceActingLanguage = new HashSet<VoiceActingLanguage>();
        }
    
        public int IdGame { get; set; }
        public string Poster { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateRelease { get; set; }
        public Nullable<int> IdDeveloper { get; set; }
        public Nullable<int> IdPublisher { get; set; }
        public Nullable<int> IdTypeEdition { get; set; }
        public Nullable<int> IdStatusCrack { get; set; }
        public string Description { get; set; }
        public int CountViews { get; set; }
        public Nullable<int> IdTypeTablet { get; set; }
        public Nullable<int> IdSystemRequipment { get; set; }
        public string URLTrailer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentsGame> CommentsGame { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavotritesGame> FavotritesGame { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarkGame> MarkGame { get; set; }
        public virtual Developers Developers { get; set; }
        public virtual Publishers Publishers { get; set; }
        public virtual StatusCrack StatusCrack { get; set; }
        public virtual SystemRequirements SystemRequirements { get; set; }
        public virtual TypesEdition TypesEdition { get; set; }
        public virtual TypeTablet TypeTablet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GamesToGenres> GamesToGenres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GamesToPlatform> GamesToPlatform { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameTrailer> GameTrailer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterfaceLanguage> InterfaceLanguage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScreenshotsGame> ScreenshotsGame { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Torrents> Torrents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VoiceActingLanguage> VoiceActingLanguage { get; set; }
    }
}
