//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainmentX
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameTrailer
    {
        public int IdTrailer { get; set; }
        public string URLTrailer { get; set; }
        public System.DateTime Date { get; set; }
        public int IdTypeTrailer { get; set; }
        public int IdGame { get; set; }
    
        public virtual Games Games { get; set; }
        public virtual TypeTrailer TypeTrailer { get; set; }
    }
}
