//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainmentX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScreenshotsGame
    {
        public int IdScreenshot { get; set; }
        public string Foto { get; set; }
        public int IdGame { get; set; }
    
        public virtual Games Games { get; set; }
    }
}
